### ISSUE TITLE
Create a contribution.md file

### ISSUE THREAD

**Issue by Beatrix-droid** [drjaat/typewritter-effect#3]
This issue is a good first issue for first time contributors.
Create a "contribution.md" file that explains how people are supposed to contribute to the repository.

A good template to use as reference/guideline to use to create this contribution.md file is the Ruby on Rails contribution.md file available at:[https://github.com/rails/rails/blob/main/CONTRIBUTING.md]()

**Comment by Amandasilvbr** [comment]
Hey! I added a contribution guide to the project. I'm a Brazilian developer, so if there is any spelling improvement, please point it out! If anyone has any suggestions, let's talk!
